//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobSovAlytalo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilmastointi
    {
        public int IlmastointiId { get; set; }
        public Nullable<bool> IlmastoinninTila { get; set; }
        public Nullable<int> TavoiteLampo { get; set; }
        public string HuoneId { get; set; }
    }
}
